create sequence rosstinder.profiles_sequence
    start with 1
    increment by 1
    minvalue 1
    NO CYCLE
    cache 1;

create table if not exists rosstinder.users (
  chat_id           bigint NOT NULL primary key,
  status            text,
  last_favorite_num bigint,
  last_profile_num  bigint
);

create table if not exists rosstinder.profiles (
  id                bigint NOT NULL primary key default nextval('rosstinder.profiles_sequence'),
  chat_id           bigint NOT NULL,
  name              text,
  gender            text,
  description       text,
  preference        text
);

create table if not exists rosstinder.favorites (
  id            bigint generated by default as identity primary key,
  who           bigint NOT NULL,
  whom          bigint NOT NULL,
  is_like       bool
);

